# Generated by Django 4.0.4 on 2022-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_quantity', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('balcony', models.FloatField(blank=True, null=True)),
                ('bedroom', models.FloatField(blank=True, null=True)),
                ('bathroom', models.FloatField(blank=True, null=True)),
                ('hall', models.FloatField(blank=True, null=True)),
                ('kitchen', models.FloatField(blank=True, null=True)),
                ('dining_room', models.FloatField(blank=True, null=True)),
                ('living_room', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('image_2d', models.ImageField(blank=True, null=True, upload_to='2DImages')),
                ('image_3d', models.ImageField(blank=True, null=True, upload_to='3DImages')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
